import React, {useState, useEffect} from 'react'
import {Loader, Card, FormField  } from "../components";

const renderCards = ({data, title}) => {
  if(data?.length > 0){
    return data.map((post) => <Card key={post._id} {...post} />)
  }
  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
  )
};


const Home = () => {

  const [loading, setLoading] = useState(true);
  const [posts, setPosts] = useState(null);
  const [search, setSearch] = useState('hahaha');

  return (
    <section className="max-w-7xl mx-auto">
      <div >
        <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>

        <p className='mt-2 text-[#666e75] text-[14px] max-w[500px]'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>

      </div>

      <div className='mt-16'> 
        <FormField />
      </div>

      <div className='mt-10'>
        {loading? (
          <div className='flex justify-center items-center'>{Loader}</div>
        ):(
          <>
            {search && (
              <h2 className='font-medium text-[#666375] text-xl mb-3'>
                Search results for <span className='font-bold text-[#222328]'>{search}</span>
              </h2>
            )}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
              {search ? (
                <renderCards 
                  data={[]} 
                  title="No search results found" 
                />
              ):(
                <renderCards
                  data={[]}
                  title="No posts found"
                />
              )}
            </div>
          </>
      )}
      </div>
    </section>
  )
}

export default Home
